### ISSUE TITLE
The four-way handshake cannot be captured by aircrack

### ISSUE THREAD

**Issue by Venom7143** [brannondorsey/wifi-cracking#18]
I'm a Fedora 26 user and I'm new to hacking. I put the wireless card in monitor mode. Then i kill the processes using airmon-ng. Once i do this my network manager goes down and i cannot access the internet. When i try the DeAuth, the DoS attack is not established and i cannot capture a four-way handshake.

**Comment by brannondorsey** [comment]
Hm... I've heard of some network cards that can't be both in monitor mode and connected to the internet at the same time. I have no experience with Fedora so I'm not much help there :frowning_face:. Does this method work for you: https://github.com/brannondorsey/wifi-cracking/issues/15?

**Comment by Venom7143** [comment]
I did some research and found that my internal network card does not support packet injection. I have to buy a usb wireless card. Can you suggest a less expensive card that can work out of the box?

**Comment by brannondorsey** [comment]
Ah, yep, that would do it. I swear by the TP-LINK TL-WN722N but it was recently brought to my attention that the new version of this card (2.0) doesn't support monitor mode. What worse, is that there isn't a good way to tell if you are buying v1 or v2 online. You could take a gamble and [buy a used one on ebay](http://www.ebay.com/itm/TP-LINK-TL-WN722N-Wireless-N150-High-Gain-USB-Adapter-150Mbps-4-dBi-Gain-USED-1X-/122615416067?hash=item1c8c72c503:g:GbYAAOSw0YlZdpP2). Otherwise [here](http://www.wirelesshack.org/best-kali-linux-compatible-usb-adapter-dongles-2016.html) is a list of supported wifi cards. Cheers!

**Comment by Venom7143** [comment]
Thanks. That would help.
